name = "ai-workflow"
main = "src/index.ts"
compatibility_date = "2024-11-18"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "CONVERSATION_HISTORY"
id = "7c147881ce7d42b8811bfbf8c38e3ee4"

[[r2_buckets]]
binding = "R2"
bucket_name = "share"

[[workflows]]
name = "ai-workflow"
binding = "AI_WORKFLOW"
class_name = "AIWorkflow"

[env.development]
name = "ai-workflow-dev"

[env.development.ai]
binding = "AI"

[[env.development.kv_namespaces]]
binding = "CONVERSATION_HISTORY"
id = "7c147881ce7d42b8811bfbf8c38e3ee4" # TODO: Change to a dev KV ID if desired

[[env.development.r2_buckets]]
binding = "R2"
bucket_name = "share" # TODO: Change to a dev R2 bucket if desired

[[env.development.workflows]]
name = "ai-workflow-dev"
binding = "AI_WORKFLOW"
class_name = "AIWorkflow"
